### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: true
do_predict: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: dolly_train_llama31
template: llama3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /project/lerman_316/hieutn/results-llama3.1-llama-factory/sft
logging_steps: 4
save_steps: 0.3
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
report_to: wandb

### eval
eval_dataset: dolly_val_llama31
per_device_eval_batch_size: 16
predict_with_generate: true
eval_strategy: steps
eval_steps: 0.2
