### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: cnn_dailymail_train_seqkd
template: alpaca
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/full/seqkd
logging_steps: 4
save_steps: 0.3
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
report_to: wandb

### eval
eval_dataset: cnn_dailymail_val,cnn_dailymail_val_seqkd
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 0.2